server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false # No se registra a sí mismo, él es el servidor.
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/